const GetUserInfo = {
  id: 1,
  name: "내래못난호랭이라는뜻이다",
  join: "2025-01-01",
  trade_count: 13,
  report_count: 0,
  purchase_posts: 4, // 백 단에서 작업
  sale_posts: 2, // 백 단에서 작업
  completed_purchase_posts: 3, // 백 단에서 작업
  completed_sale_posts: 1, // 백 단에서 작업
  profile_picture: `${process.env.PUBLIC_URL}/images/WildSoul.png`,

  trade: [
    // id: pk
    // title: 덱 판매 제목 or 낱장 카드명
    // optiong: 'deck' or 'single'
    // quantity: if deck == 1 else 낱장은 낱장 개수
    // trade_type: 'purchase' or 'sale'
    // status: 'in_progress' or 'completed'
    // rarity: 'anything' or 'normal' or 'normal_rare' or 'super_rare' or 'ultra_rare' or
    //         'ultimate_rare' or 'secret_rare' or 'holographic_rare' or ...
    // negotiable: '1' = 흥정 가능 , '0' = 흥정 불가
    // date: "xxxx-xx-xx"
    // comment: "추가설명"
    {
      id: 1,
      title: "증식의 G",
      post_picture: `${process.env.PUBLIC_URL}/images/GrowthG.png`,
      option: "single",
      quantity: 3,
      trade_type: "purchase",
      status: "in_progress",
      rarity: "상관없음",
      price: 3000,
      negotiable: 0,
      date: "2025-01-01",
      comment: "지역 가까우면 직거래 가능 , DM 주세요.",
    },
    {
      id: 2,
      title: "텐 사우전드 드래곤",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "single",
      quantity: 1,
      trade_type: "purchase",
      status: "in_progress",
      rarity: "",
      price: 100000,
      negotiable: 1,
      date: "2025-01-07",
      comment: "DM 주세요",
    },
    {
      id: 3,
      title: "천년 데먼스미스 스네이크아이 덱 삽니다.",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "deck",
      quantity: 1,
      trade_type: "purchase",
      status: "in_progress",
      rarity: "",
      price: 50000,
      negotiable: 1,
      date: "2025-01-11",
      comment: "DM 주세요",
    },
    {
      id: 4,
      title: "스타더스트 드래곤",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "single",
      quantity: 2,
      trade_type: "purchase",
      status: "in_progress",
      rarity: "",
      price: 20000,
      negotiable: 1,
      date: "2025-01-12",
      comment: "지역 가까우면 직거래 가능 , DM 주세요",
    },
    {
      id: 5,
      title: "유벨 덱 팝니다.",
      post_picture: `${process.env.PUBLIC_URL}/images/유벨.png`,
      option: "deck",
      quantity: 1,
      trade_type: "sale",
      status: "in_progress",
      rarity: "",
      price: 130000,
      negotiable: 1,
      date: "2025-01-20",
      comment: "배송비 별도",
      deck_list: [
        {
          id: 1,
          card_name: "증식의 G",
          rarity: "레어",
        },
        {
          id: 2,
          card_name: "증식의 G",
          rarity: "노말",
        },
        {
          id: 3,
          card_name: "증식의 G",
          rarity: "울트라",
        },
      ],
    },
    {
      id: 6,
      title: "개같은 덱 팝니다.",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "deck",
      quantity: 1,
      trade_type: "sale",
      status: "in_progress",
      rarity: "",
      price: 80000,
      negotiable: 0,
      date: "2025-01-08",
      comment: "ㅁㅌ 가능",
    },
    {
      id: 7,
      title: "메멘토 덱 삽니다.",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "deck",
      quantity: 1,
      trade_type: "purchase",
      status: "completed",
      rarity: "",
      price: 75000,
      negotiable: 0,
      date: "2025-01-12",
      comment: "",
    },
    {
      id: 8,
      title: "욕망의 항아리",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "single",
      quantity: 5,
      trade_type: "purchase",
      status: "completed",
      rarity: "",
      price: 2000,
      negotiable: 0,
      date: "2025-01-14",
      comment: "",
    },
    {
      id: 9,
      title: "요선수 덱 팝니다.",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "deck",
      quantity: 1,
      trade_type: "sale",
      status: "completed",
      rarity: "",
      price: 15000,
      negotiable: 0,
      date: "2025-01-03",
      comment: "",
    },
    {
      id: 10,
      title: "격류장",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "single",
      quantity: 4,
      trade_type: "sale",
      status: "in_progress",
      rarity: "울트라",
      price: 500,
      negotiable: 0,
      date: "2025-01-09",
      comment: "",
    },
    {
      id: 11,
      title: "날개 크리보",
      post_picture: `${process.env.PUBLIC_URL}/images/하루우라라.png`,
      option: "single",
      quantity: 3,
      trade_type: "sale",
      status: "completed",
      rarity: "레어",
      price: 1500,
      negotiable: 0,
      date: "2025-01-01",
      comment: "",
    },
  ],
};

export default GetUserInfo;
